# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = app
TARGET = 06_Dialog
DESTDIR = ../../x64/Debug
QT += core gui widgets
CONFIG += C++11
LIBS += -L"."
DEPENDPATH += .
MOC_DIR += .
OBJECTS_DIR += debug
UI_DIR += GeneratedFiles
RCC_DIR += GeneratedFiles
HEADERS += ./MainWindow.h
SOURCES += ./MainWindow.cpp \
    ./main.cpp
