# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = app
TARGET = 05_QMainWindow
DESTDIR = ../../x64/Debug
QT += core gui widgets
CONFIG += debug
LIBS += -L"."
DEPENDPATH += .
MOC_DIR += .
OBJECTS_DIR += debug
UI_DIR += .
RCC_DIR += .
HEADERS += ./MainWindow.h
SOURCES += ./MainWindow.cpp \
    ./main.cpp
