# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = app
TARGET = 08_Layout
DESTDIR = ../../x64/Debug
QT += core gui widgets
CONFIG += C++11
LIBS += -L"."
DEPENDPATH += .
MOC_DIR += .
OBJECTS_DIR += debug
UI_DIR += ./UI
RCC_DIR += .
HEADERS += ./MainWindow.h
SOURCES += ./MainWindow.cpp \
    ./main.cpp
FORMS += ./MainWindow.ui
RESOURCES += MainWindow.qrc
